import { Application } from "./src/Application.js";
import type { ApplicationOptions, Polling } from "./src/Application.js";
import { Bot, BotApiError, retryUnknownOutcome } from "./src/BotApi.js";
import type { BotApiOptions, MessageDefaults } from "./src/BotApi.js";
import {
  callbackData,
  CallbackDataInvalid,
  CallbackDataTooLong,
} from "./src/CallbackData.js";
import type { CallbackData, CallbackDataMatch } from "./src/CallbackData.js";
import { answerCallback, callbackTarget } from "./src/CallbackQuery.js";
import type { AnswerCallbackOptions, CallbackTarget } from "./src/CallbackQuery.js";
import { reply, replyTo, respond, respondTo } from "./src/Conversation.js";
import type {
  ConversationMessage,
  ConversationMessageOptions,
  ConversationTarget,
  ReplyOptions,
  ReplyTarget,
} from "./src/Conversation.js";
import { downloadFile } from "./src/Files.js";
import type { DownloadFileOptions } from "./src/Files.js";
import { html, markdownV2 } from "./src/Formatting.js";
import {
  messageEntities,
  messageMedia,
  messageReply,
  messageSender,
  messageText,
} from "./src/Message.js";
import type {
  MessageEntitySpan,
  MessageMedia,
  MessageReply,
  MessageSender,
} from "./src/Message.js";
import { InboxLeaseLost, InboxStore, InboxStoreError, MemoryInbox } from "./src/Inbox.js";
import type {
  ClaimedUpdate,
  ClaimInboxUpdates,
  InboxLeaseOptions,
  InboxLeaseResult,
  FencedInboxOperation,
  InboxSaveResult,
  InboxOptions,
  InboxSettlement,
  InboxStoreService,
  PruneInboxUpdates,
  SaveInboxUpdate,
  SettleInboxUpdate,
} from "./src/Inbox.js";
import {
  defineJobs,
  InvalidJobPayload,
  InvalidJobSchedule,
  job,
  JobCapacityExceeded,
  JobConflict,
  JobLeaseLost,
  JobStore,
  JobStoreError,
  MemoryJobs,
} from "./src/Jobs.js";
import type {
  ClaimedJob,
  ClaimJobs,
  FencedJobOperation,
  JobContext,
  JobDefinition,
  JobLeaseOptions,
  JobLeaseResult,
  JobOptions,
  JobSaveResult,
  JobSchedule,
  JobSettlement,
  JobStoreService,
  Jobs,
  PruneJobs,
  SaveJob,
  ScheduleJobOptions,
  SettleJob,
} from "./src/Jobs.js";
import {
  conversation,
  Conversation,
  ConversationConflict,
  ConversationScopeMissing,
  conversations,
  ConversationStateInvalid,
} from "./src/Conversations.js";
import type {
  ConversationEnd,
  ConversationNext,
  ConversationStep,
  DurableConversation,
} from "./src/Conversations.js";
import {
  ConversationStore,
  ConversationStoreError,
  MemoryConversations,
} from "./src/ConversationStore.js";
import type {
  CommitConversation,
  ConversationCommitExpected,
  ConversationCommitResult,
  ConversationRecord,
  ConversationStoreService,
  LoadConversation,
} from "./src/ConversationStore.js";
import { SqliteInbox } from "./src/SqliteInbox.js";
import type { SqliteInboxOptions, SqliteInboxStore } from "./src/SqliteInbox.js";
import { SqliteJobs } from "./src/SqliteJobs.js";
import type { SqliteJobsOptions, SqliteJobStore } from "./src/SqliteJobs.js";
import { SqliteConversations } from "./src/SqliteConversations.js";
import type {
  SqliteConversationsOptions,
  SqliteConversationStore,
} from "./src/SqliteConversations.js";
import { PollingConflictError, pollInboxUpdates, pollUpdates } from "./src/Polling.js";
import type {
  AcknowledgmentMode,
  InboxPollingOptions,
  PollingOptions,
  UpdateHandler,
} from "./src/Polling.js";
import {
  callbackQuery,
  chatType,
  command,
  defineBot,
  entity,
  every,
  Filter,
  media,
  mention,
  on,
  regex,
  repliedMessage,
  routes,
  text,
} from "./src/Routing.js";
import type { Webhook, WebhookOptions } from "./src/Webhook.js";
import type {
  CallbackQueryMatch,
  BotDefinition,
  ChatTypeMatch,
  CommandMatch,
  EntityMatch,
  MediaKind,
  MediaKindMap,
  MediaMatch,
  MessageChatType,
  RegexMatch,
  RepliedMessageMatch,
  Route,
  TextMatch,
} from "./src/Routing.js";
import { updateContext } from "./src/Update.js";
import type { UpdateContext } from "./src/Update.js";

export * from "./src/methods.generated.js";
export * from "./src/types.generated.js";
export {
  answerCallback,
  Application,
  Bot,
  BotApiError,
  callbackData,
  CallbackDataInvalid,
  CallbackDataTooLong,
  callbackQuery,
  callbackTarget,
  chatType,
  command,
  conversation,
  Conversation,
  ConversationConflict,
  ConversationScopeMissing,
  conversations,
  ConversationStateInvalid,
  ConversationStore,
  ConversationStoreError,
  defineBot,
  defineJobs,
  downloadFile,
  InboxLeaseLost,
  entity,
  every,
  Filter,
  html,
  InboxStore,
  InboxStoreError,
  InvalidJobPayload,
  InvalidJobSchedule,
  job,
  JobCapacityExceeded,
  JobConflict,
  JobLeaseLost,
  JobStore,
  JobStoreError,
  media,
  messageEntities,
  messageMedia,
  messageReply,
  messageSender,
  messageText,
  mention,
  markdownV2,
  MemoryInbox,
  MemoryConversations,
  MemoryJobs,
  on,
  pollInboxUpdates,
  pollUpdates,
  PollingConflictError,
  reply,
  replyTo,
  retryUnknownOutcome,
  regex,
  repliedMessage,
  respond,
  respondTo,
  routes,
  SqliteInbox,
  SqliteConversations,
  SqliteJobs,
  text,
  updateContext,
};
export type {
  AcknowledgmentMode,
  AnswerCallbackOptions,
  ApplicationOptions,
  BotApiOptions,
  BotDefinition,
  CallbackData,
  CallbackDataMatch,
  CallbackTarget,
  ClaimedJob,
  ClaimJobs,
  ClaimedUpdate,
  ClaimInboxUpdates,
  ChatTypeMatch,
  ConversationTarget,
  ConversationMessageOptions,
  CommitConversation,
  ConversationCommitExpected,
  ConversationCommitResult,
  ConversationEnd,
  ConversationMessage,
  ConversationNext,
  ConversationRecord,
  ConversationStep,
  ConversationStoreService,
  InboxLeaseOptions,
  InboxLeaseResult,
  DownloadFileOptions,
  DurableConversation,
  EntityMatch,
  FencedInboxOperation,
  FencedJobOperation,
  InboxSaveResult,
  InboxOptions,
  InboxPollingOptions,
  InboxSettlement,
  InboxStoreService,
  JobContext,
  JobDefinition,
  JobLeaseOptions,
  JobLeaseResult,
  JobOptions,
  JobSaveResult,
  JobSchedule,
  JobSettlement,
  JobStoreService,
  Jobs,
  MediaKind,
  MediaKindMap,
  MediaMatch,
  MessageDefaults,
  MessageEntitySpan,
  MessageMedia,
  MessageReply,
  MessageSender,
  MessageChatType,
  PollingOptions,
  Polling,
  PruneInboxUpdates,
  PruneJobs,
  Route,
  SaveInboxUpdate,
  SaveJob,
  ScheduleJobOptions,
  SettleInboxUpdate,
  SettleJob,
  SqliteInboxOptions,
  SqliteInboxStore,
  SqliteConversationsOptions,
  SqliteConversationStore,
  SqliteJobsOptions,
  SqliteJobStore,
  RegexMatch,
  RepliedMessageMatch,
  ReplyOptions,
  ReplyTarget,
  TextMatch,
  LoadConversation,
  UpdateHandler,
  UpdateContext,
  Webhook,
  WebhookOptions,
  CallbackQueryMatch,
  CommandMatch,
};
export * as Effect from "effect/Effect";
export * as Schema from "effect/Schema";
